//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCSDL_QLSach.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucVu
    {
        public int IdChucVu { get; set; }
        public string ChucVu1 { get; set; }
    }
}
