//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCSDL_QLSach.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int IdThanhToan { get; set; }
        public string TenKhach { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> MaSach { get; set; }
        public Nullable<int> MaTG { get; set; }
        public Nullable<int> MaNXB { get; set; }
        public Nullable<double> GiaSach { get; set; }
    }
}
